# Generated by Django 3.0.3 on 2020-05-18 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('q1', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 5, 18, 18, 33, 22, 677462, tzinfo=utc))),
            ],
        ),
    ]
