# Generated by Django 3.0.3 on 2020-05-18 23:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200519_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 23, 39, 19, 142177, tzinfo=utc)),
        ),
    ]
