# Generated by Django 3.0.3 on 2020-05-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200523_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='job',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='organ',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='q1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='q10',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='q11',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='q12',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='q2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='q3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='q4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='q5',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='q6',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='q7',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='q8',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='q9',
            field=models.TextField(default=''),
        ),
    ]
